### ISSUE TITLE
Is it possible to control morphing operation and export ?

### ISSUE THREAD

**Issue by kangyeolk** [Nuthouse01/PMX-VMD-Scripting-Tools#18]
First, thank you for your amazing work!
I wonder that i can utilize your code for controlling morphing operation and export it as a .png
I am trying to make a dataset for animation talking head alike below project:

https://pkhungurn.github.io/talking-head-anime/

So, I need to control the morphing and corresponding image. Can I get any recommendation to do this?

**Comment by Nuthouse01** [comment]
Sadly, my package does not support rendering any models. So you cannot use this to create PNG images. Even if my package could help with other things, you would still need to manually load everything in MMD and render it.
This code does read the data from the entire model, so you *could* write your own renderer that uses this data, but I'm not volunteering to do it.
Looking at section 5.1 in the page you linked, about Dataset Annotation, my code would not solve any of these tasks. Locating where the head "is" is a very subjective task, that would require a real human to look at the model. I could identify "all vertices that are controlled by the head bone" and draw a bounding box around that, but that is not guaranteed to succeed (what if they have an exceptionally large hat?). Or I could identify "all vertices that are included in the 'face' material", but that's no help because each model uses a different name for the 'face' material. Similarly, my code could identify the names of the "wink" morphs in the model, and say which a model includes or does not include, but it would require a real human looking at the model to determine if they are "smile wink" or "normal wink" morphs, which defeats the purpose of automating it.

**Comment by kangyeolk** [comment]
Thank you for your kind and detailed answer!
