### ISSUE TITLE
Suggestion: Add auto-hands-twist

### ISSUE THREAD

**Issue by cuongdq0511** [Nuthouse01/PMX-VMD-Scripting-Tools#19]
Hey sorry if i put this in the wrong place, i don't use Github and created this account just to suggest to you guys.
I'd be nice to have a auto-hands-twist, since auto-arms-twist is possible.

Also fantastic work guys. Thank you for this helping tool.

**Comment by Nuthouse01** [comment]
Hello! Nobody is using the "issues" section to share or track actual bugs/problems so it's whatever :)
The current auto arm twist script/system applies to the whole arm, both the upper arm and the lower arm. Specifically, any twisting on the upper arm bone is smoothly distributed between the upper arm bone and elbow bone, and any twisting on the elbow bone is smoothly distributed between the elbow bone and wrist bone.
The flaw in the current system (that I have known about since I first designed it) is the wrist bones. Ideally, and twisting on the wrist bone would be smoothly distributed between the elbow bone and wrist bone, but it turns out that this is EXTREMELY hard to successfully do. I would love to fix this, I can't have a truly perfect armtwist system until I fix this, but I simply don't know how. If you can give me examples of models that have this feature/behavior, I can try to copy those structures/tricks but they're not always transferable.

To get into even more detail, there are 2 approaches to doing the automatic armtwist. The first way (the one that I copied from Quappa-El and the one that my "bone_auto_armtwist" script uses) is to hijack the semistandard armtwist system (3 hidden bones spaced along each arm section that inherit varying amounts of motion from the "armtwist" bone). The second way (every model with auto armtwist that isn't Quappa-El or me) is to use SDEF weighting, and the whole arm section is controlled by only two bones. The script "WIP_pmx_magic_armtwist" script attempts to install this kind of armtwist system, but because it requires programmatically re-weighting the entire arm segments it occasionally f***s up, which is why that script was never finalized. 
I did just discover some models by Tamo (https://3d.nicovideo.jp/users/2851800) and his models DO have this mythical Holy Grail feature that lets them distribute the wrist twist upstream between the elbow and wrist, but that feature is integrally tied to the second/SDEF-based armtwist system. I don't think I can transfer that trick to the first approach.

**Comment by Nuthouse01** [comment]
Actually, you got me re-thinking about this problem. And I luckily stumbled into a solution! Download v6.01 of the package. The auto-armtwist script creates some additional new structures that fix the wrist pinching problem! And as I planned, I figured out how to steal Tamo's idea to make the SDEF kind of auto-arm-twist system also fix the wrist pinching problem.
