### ISSUE TITLE
Some explanation about interpolation

### ISSUE THREAD

**Issue by alient12** [Nuthouse01/PMX-VMD-Scripting-Tools#35]
First of all thank you for your great work!
I'm using the script to convert `.vmd` to `.txt` and my problem is about interpolation part.
two rows of output file is:
```
bone_name,frame_num,Xpos,Ypos,Zpos,Xrot,Yrot,Zrot,phys_disable,interp_x_ax,interp_x_ay,interp_x_bx,interp_x_by,interp_y_ax,interp_y_ay,interp_y_bx,interp_y_by,interp_z_ax,interp_z_ay,interp_z_bx,interp_z_by,interp_r_ax,interp_r_ay,interp_r_bx,interp_r_by
グルーブ,31,0.0,-0.13999998569488525,0.0,-0.0,-0.0,-0.0,False,20,20,107,107,20,20,107,107,20,20,107,107,20,20,107,107
グルーブ,42,0.0,-0.10499995946884155,0.0,-0.0,-0.0,-0.0,False,36,0,93,127,36,0,93,127,36,0,93,127,36,0,93,127
```
I want to understand what exactly interp_z_ax, interp_z_ay, interp_z_bx and interp_z_by are. I know they are about position of z in two different times and I have to use them to draw the curve between them.

I'm already familiar with Newton's interpolation method that only coordination of points are important but here **can't understand what ax, ay, bx, by are**. I would really appreciate if you give me some clue .

**Comment by Nuthouse01** [comment]
Hello! The explanation here is very simple.

When using MikuMikuDance, the interpolation curve is the graph in the bottom left. The line always goes through the bottom-left corner and top-right corner. There are two other points that you can move to control the shape of this line, I call these point A (closer to bottom-left) and point B (closer to top-right). `interp_?_ax` sets the X-position of point A within this graph. `interp_?_ay` sets the Y-position of point A within this graph. And then the same for `bx`, `by`. The X and Y position have a range of [0, 127] and are always integers. The `?` part is because you can specify separate interpolation curves for x-motion, y-motion, z-motion, and rotation.

Now that you know where the points are, how does the program use them to draw the curve you see? Also simple. It uses **bezier curve** math. The four control points for the curve are the bottom-left corner (0,0), point A, point B, and the top-right corner (I was never able to prove whether the top-right corner uses 127,127 or 128,128). I implemented code for dealing with these bezier curves in `nuthouse01_core.py` class `class MyBezier(object)`, if seeing my code helps you at all.
